[build]
  publish = "public"
  functions = "netlify/functions"

[functions."info"]
  timeout = 26

[functions."download"]
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
